### PR TITLE
Update/fix for move

### LINKED ISSUE #2: Deployment documentation needs finalized
* We should have a guide for facilitators on how to build the workshop for delivery.
* This guide should include basic setup, customization, and some troubleshooting.

### LINKED ISSUE #6: Convert existing GPTE operators to RedHatGov operators
We are rehoming the RedHatGov operators and promoting them to support the workshop, so we need to migrate the workshop away from the old operators.

This has a lot of implications, specifically around automatic naming of routes based on `Project`-`CR` names. We need to ensure that as we make this migration we're setting those values appropriately so that nothing breaks with references to the old routes (specifically the lab guides have these often hard-coded)

### LINKED ISSUE #8: Workflow for archived/unused roles need identified
We have several vestigal roles right now that shouldn't be deployed with the workshop.

Should we:
1. Simply default them to off and document that they're untested and may not work
2. Relocate them within this repository to an "archive" folder
3. Remove them from this repository and maintain a separate "OpenShift Roles" repository that contains the roles we aren't testing/maintaining as much
4. Just remove them entirely

### LINKED ISSUE #10: Quay is broken again
Something in Quay has changed dramatically enough that it's not working right.

* There's something wrong with the route, I was getting HSTS errors
* I want to specifically explore how we've been doing certificates, which I believe is a big part of the problem

### LINKED ISSUE #12: Move all Letsencrypt logic into `provision.yml`
To align self-provisioning with RHPDS-provisioning, I'd like to move `letsencrypt` into `provision.yml`.

Specifically the reason for this is that I hope that fixing #10 puts us in a state where Quay is no longer a special snowflake and can instead inherit cluster default certs. If this works out, it won't make sense to keep everything in `common.yml` and the cert logic can be dramatically simplified (which would be great).

### PR DESCRIPTION
**Pull request by jharmison-redhat**
- [x] Remove dual-methods of running workshops (unnecessary)
- [x] Convert all references from `jharmison-redhat` to `RedHatGov` where appropriate
- [x] Migrate from old GPTE & community operators to new RedHatGov operators
  - [x] Gitea
  - [x] Sonarqube
  - [x] Nexus
- [x] Remove the following:
  - [x] OCS (Let's not add this complexity, was already optional)
  - [x] Service Mesh (Leave that to the SM workshop)
  - [x] 3scale (was always a fun project, not related to openshift-tasks)
  - [x] bookinfo (was a demo of the above + SM)
- [x] Refine README to make deployment better understood
- [x] Add new section to README to specifically cover a "Quickstart" (ref issue #2 discussion)
- [x] Fix Quay (Route shenanigans again!)
- [x] Migrate letsencrypt into provision to better align self-provisioned and RHPDS cluster behavior

fixes #2
fixes #6 
fixes #8 
fixes #10
fixes #12

### CODE REVIEW

**Comment by jharmison-redhat** [comment]
I have now successfully deployed a _completely default_ cluster by following the basic steps listed in the README for both the quick start on RHPDS and a self-provisioned cluster.

The lab guides need some tweaking to address a couple of these changes, most notably that `skopeo` in Lab 16 points to the Quay `Service` on HTTPS but we've managed to shift TLS to `Edge` on the Quay route through the operator.

Would appreciate reviews by at least two people along with test deployments on your platform of choice before a merge. OpenSCAP is about to get rebased on this PR as it stands right now and work on that will be finished between customers and other project time this week.

**Review by mbach04 — DISMISSED** [review]
Something dorked with the route concatenation I'm guessing. (Didn't get the chance to dig into the cause).
But, what I observed running the defaults, following the README to the letter was the following:
Setting my common.yml vars as:
```
cluster_name: cluster-473b
openshift_base_domain: 473b.example.opentlc.com
```
Resulted in the following routes being created:
```
console.apps.openshift.example.com
quay.apps.openshift.example.com
```
Which timeout of course

**Comment by jharmison-redhat** [comment]
> ```
> cluster_name: cluster-473b
> openshift_base_domain: 473b.example.opentlc.com
> ```
> 
> Resulted in the following routes being created:
> 
> ```
> console.apps.openshift.example.com
> quay.apps.openshift.example.com
> ```

If you were working from fresh examples and setting the appropriate vars, I don't believe this would have happened. If you attempted to adapt old vars files, I could see this happening.

Able to confirm you were using completely fresh vars from the updated examples?

**Comment by jharmison-redhat** [comment]
I've created a gist with a small script I use for multi-branch testing:
https://gist.github.com/jharmison-redhat/902e901ae46d1b1d9159c449c021460d

Using this script in `vars/vars.py` and with a file in `vars/rhpds_template.yml` containing the following content:
```yaml
common.yml:
  openshift_base_domain: ee4c.example.opentlc.com
  cluster_name: cluster-ee4c
  manual_users:
  - username: james
    password: <my password>
    admin: yes
  number_of_users: "5"
devsecops.yml:
  reg_rhio_pull_token : <my actual pull token>
```
running `vars/vars.py` creates a folder named `rhpds` with a `common.yml` and `devsecops.yml` using the default values from the examples with these overrides set.

That may help you with multi-branch variable setting, @mbach04

**Comment by mbach04** [comment]
Definitely something related to the file changes not persisting. I am working on a checkout of your PR though. Running a new test now to confirm.

**Review by andykrohg — APPROVED** [review]

**Pull request merged**
